apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: controller-manager-pdb
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: sts-leader-elect-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  minAvailable: 1
  selector:
    matchLabels:
      control-plane: controller-manager